version: '3.3'

services:
  keycloak:
    image: jboss/keycloak
    env_file: ./.env
    restart: unless-stopped
    volumes:
      - data:/opt/jboss/keycloak/standalone/data/
    ports:
      - '8080:8080'
      - '8443:8443'

networks:
  default:
    name: nginxpm
    external: true

volumes:
  data:
